[features]
seeds = false
skip-lint = false
[programs.localnet]
proof_of_work_faucet = "PoWSNH2hEZogtCg1Zgm51FnkmJperzYDgPK4fvs8taL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/x/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
